# Generated by Django 4.2.1 on 2023-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='imagie',
            field=models.ImageField(upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
