# Generated by Django 4.1.7 on 2023-06-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_special_games_remove_games_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='imagie',
            new_name='image',
        ),
    ]
