# Generated by Django 4.1.7 on 2023-06-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondgames', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametest',
            old_name='imagie',
            new_name='image',
        ),
    ]
